#!/usr/bin/zsh
sleep $((RANDOM%15+5))m

#BORG_PRUNE_DAILY="21"
#BORG_PRUNE_MONTHLY="6"
#BORG_REPO="<repo-url>"
#BORG_BACKUP_DIR="/dir1 /dir2"
#export BORG_PASSPHRASE=""

echo -n "## BORGbackup - ";  date +%F
if type borg > /dev/null 2>&1; then
 echo -n "## Starting at: "; date +%H:%M
 echo "## BORG Repository: $BORG_REPO"
 echo "## Backup directories: $BORG_BACKUP_DIR"
 borg create -s -e "*/nobackup/" $BORG_REPO::{hostname}-{now} ${=BORG_BACKUP_DIR}
 echo "## BORG Repository Cleanup: Keep $BORG_PRUNE_MONTHLY monthly/$BORG_PRUNE_DAILY daily backups"
 borg prune --stats --list --keep-monthly $BORG_PRUNE_MONTHLY --keep-daily $BORG_PRUNE_DAILY "$BORG_REPO"
 echo "## BORG Repository Cleanup: finished"
 echo -n "## Finished at: "; date +%H:%M
else
 echo "## borgbackup not found - please install"
fi
