# vim:ft=ansible:
---
- name: restart smtpd
  service: name=smtpd state=restarted
  #- name: rebuild smtpd table aliases
  #command: makemap /etc/smtpd/aliases
  #become: true

- name: reload smartd
  service: name=smartd state=reloaded
  
- name: reload unbound
  service: name=unbound state=reloaded

- name: rebuild locales
  command: locale-gen
