---
- name: /etc/skel/.zshrc.pre
  copy:
    src:    zshrc.pre
    dest:   "/etc/skel/.zshrc.pre"

- name: /etc/skel/.zshrc
  copy:
    src:    zshrc
    dest:   "/etc/skel/.zshrc"

- name: "/etc/profile.d/loginmail.sh"
  template:
    src:  "loginmail.sh.j2"
    dest: "/etc/profile.d/loginmail.sh"
  when: adminmail is defined
