---
- name: /etc/skel/.zshrc
  copy:
    src:    zshrc
    dest:   "/etc/skel/.zshrc"

- name: /etc/skel/.zshrc.local
  copy:
    src:    zshrc.local
    dest:   "/etc/skel/.zshrc.local"

- name: "/etc/zsh/zprofile"
  copy:
    src:  zprofile
    dest: "/etc/zsh/zprofile"
  when: ansible_distribution == "Debian"

- name: "/etc/zprofile"
  copy:
    src:  zprofile
    dest: "/etc/zprofile"
  when: ansible_facts['os_family']|lower == 'suse'

- name: "/etc/profile.d/loginmail.sh"
  template:
    src:  "loginmail.sh.j2"
    dest: "/etc/profile.d/loginmail.sh"
  when: adminmail is defined
