---
- name: /etc/skel/.zshrc
  copy:
    src:    zshrc
    dest:   "/etc/skel/.zshrc"

- name: /etc/skel/.zshrc.local
  copy:
    src:    zshrc.local
    dest:   "/etc/skel/.zshrc.local"

- name: "/etc/zsh/zprofile"
  template:
    src:  "zprofile.j2"
    dest: "/etc/zsh/zprofile"
  when: ansible_distribution == "Debian"

- name: "/etc/zprofile"
  template:
    src:  "zprofile.j2"
    dest: "/etc/zprofile"
  when: ansible_distribution != "Debian"
