# vim:ft=ansible:
---
- name: install rsyslog packages
  pacman: name="rsyslog" state=present

# ensuring systemd-journald is forwarding to syslog socket
- name: /etc/systemd/journald.conf - forwarding to syslog socket
  lineinfile:
    path:   "/etc/systemd/journald.conf"
    regexp: "^ForwardToSyslog=yes"
    line:   "ForwardToSyslog=yes"
  notify:
    - restart journald

- name: /etc/rsyslog.conf
  template:
    src:    rsyslog.conf.j2
    dest:   /etc/rsyslog.conf
    owner:  root
    group:  root
    mode:   0644
  notify:
    - restart rsyslogd

