#!/bin/bash

echo "Backup MariaDB Database $(date +%F) (via mysqldump)..."

echo "Running mysqldump"
time mysqldump --single-transaction --quick --lock-tables=false --all-databases > mariadb-full-backup-$(date +%F).sql

echo "Compress via bzip2"
time bzip2 /backup/mariadb/mysqldump/mariadb-full-backup-$(date +%F).sql

