#!/bin/bash

umask 077
BACKUP_PATH=/backup/mariadb/mysqldump/
cd $BACKUP_PATH || {
	echo "Unable to access $BACKUP_PATH"
	exit 1
}

echo "Backup MariaDB Database $(date +%F) to $BACKUP_PATH (via mysqldump)..."
echo -n "Starting at: "; date +%H:%M

echo "Running mysqldump:"
mysqldump --single-transaction --quick --lock-tables=false --all-databases > "mariadb-full-backup-$(date +%F).sql"

echo "Compressing via gzip:"
gzip "mariadb-full-backup-$(date +%F).sql"

echo -n "Finished at: "; date +%H:%M
