---
# Nextcloud cronjob
- name: /etc/cron.d/nextcloud
  copy:
    content:  |
      MAILTO=root
      SHELL=/bin/bash
      NEXTCLOUD_PATH="{{ nextcloud_path }}"
      */5 * * * *  www-data if [ -e "$NEXTCLOUD_PATH/cron.php" ]; then sleep $((RANDOM\%60))s; php -f "$NEXTCLOUD_PATH/cron.php"; fi
    dest:     /etc/cron.d/nextcloud
    mode:     0644
    owner:    root
    group:    root
