---
- name: "server: load variables"
  include_vars: "server.yml"

- name: "server: install packages: {{install_packages}}"
  zypper:
    name: "{{install_packages}}"
    state: present

- name: "server: remove packages: {{ remove_packages }}"
  zypper:
    name: "{{ remove_packages }}"
    state: absent
