---
- name: repositories for suse
  zypper_repository:
    name:             "{{ item.name | default(name) }}"
    repo:             "{{ item.repo | default(repo) }}"
    state:            "{{ item.state | default(omit) }}"
    auto_import_keys: "{{ item.auto_import_keys | default(auto_import_keys) }}"
    runrefresh: yes
    priority:         "{{ item.priority | default(priority) }}"
  with_flattened:
    - "{{ zypper_repo_list }}"
    - "{{ zypper_repo_host }}"
    - "{{ zypper_repo_group }}"

- name: "Repositories for OpenSUSE Tumbleweed"
  block:
    - zypper_repository:
        name:     "Tumbleweed-oss"
        repo:     "http://download.opensuse.org/tumbleweed/repo/oss"
        state:    "present"
        priority: 90
    - zypper_repository:
        name:     "Tumbleweed-non-oss"
        repo:     "http://download.opensuse.org/tumbleweed/repo/non-oss"
        state:    "present"
        priority: 90
  when:
    - ansible_distribution == 'openSUSE Tumbleweed'

- name: "Repositories for OpenSUSE Leap"
  block:
    - zypper_repository:
        name:     "OpenSUSE-oss"
        repo:     "http://download.opensuse.org/distribution/leap/$releasever/repo/oss/"
        state:    "present"
        priority: 90
    - zypper_repository:
        name:     "OpenSUSE-update-oss"
        repo:     "http://download.opensuse.org/update/leap/$releasever/oss"
        state:    "present"
        priority: 90
    - zypper_repository:
        name:     "OpenSUSE-non-oss"
        repo:     "http://download.opensuse.org/distribution/leap/$releasever/repo/non-oss/"
        state:    "present"
        priority: 90
    - zypper_repository:
        name:     "OpenSUSE-update-non-oss"
        repo:     "http://download.opensuse.org/update/leap/$releasever/non-oss/"
        state:    "present"
        priority: 90
    - zypper_repository:
        name:     "OpenSUSE-update-backports"
        repo:     "http://download.opensuse.org/update/leap/$releasever/backports/"
        state:    "present"
        priority: 90
# needed since 15.3 because 15.3 pulls packages from SLE
      when: ansible_distribution_version|float >= 15.3
    - zypper_repository:
        name:     "OpenSUSE-update-sle"
        repo:     "http://download.opensuse.org/update/leap/$releasever/sle/"
        state:    "present"
        priority: 90
# needed since 15.3 because 15.3 pulls packages from SLE
      when: ansible_distribution_version|float >= 15.3
    - zypper_repository:
        name:   "repo-oss"
        state:  "absent"
    - zypper_repository:
        name:   "repo-non-oss"
        state:  "absent"
    - zypper_repository:
        name:   "repo-update"
        state:  "absent"
    - zypper_repository:
        name:   "repo-update-non-oss"
        state:  "absent"
    - zypper_repository:
        name:   "repo-backports-update"
        state:  "absent"
    - zypper_repository:
        name:   "repo-sle-update"
        state:  "absent"
  when:
    - ansible_distribution == 'openSUSE Leap'
