---
- name: repositories for suse
  zypper_repository:
    name:             "{{ item.name | default(name) }}"
    repo:             "{{ item.repo | default(repo) }}"
    state:            "{{ item.state | default(omit) }}"
    auto_import_keys: "{{ item.auto_import_keys | default(auto_import_keys) }}"
    runrefresh: yes
  with_flattened:
    - "{{ zypper_repo_list }}"
    - "{{ zypper_repo_host }}"
    - "{{ zypper_repo_group }}"

#zypper_repo_group:
#  - name:             "OpenSUSE-oss"
#    repo:             "http://download.opensuse.org/distribution/leap/{{ ansible_distribution_version }}/repo/oss/"
#   state:            "present"
#   auto_import_keys: "yes"
#   priority:         90

- name: "Repositories for OpenSUSE Tumbleweed"
  block:
    - zypper_repository:
        name:     "Tumbleweed-oss"
        repo:     "http://download.opensuse.org/tumbleweed/repo/oss"
        state:    "present"
        priority: 90
    - zypper_repository:
        name:     "Tumbleweed-non-oss"
        repo:     "http://download.opensuse.org/tumbleweed/repo/non-oss"
        state:    "present"
        priority: 90
  when:
    - ansible_distribution == 'openSUSE Tumbleweed'
