# vim:ft=yaml.ansible
---
- include_tasks: variables.yml

- name: sudo configuration
  template:
    src:      "sudoers.j2"
    dest:     "{{ sudo_config_file }}"
    owner:    "root"
    group:    "wheel"
    mode:     0440
    backup:   yes
    validate: visudo -cf %s
