# vim:ft=yaml.ansible
---
- include_tasks: variables.yml

- name: "install package: {{ sudo_package }}"
  package:
    name:   "{{ sudo_package }}"
    state:  present

- name: "{{ sudo_config_file }}"
  template:
    src:      "sudoers.j2"
    dest:     "{{ sudo_config_file }}"
    owner:    "root"
    group:    "root"
    mode:     0440
    backup:   yes
    validate: visudo -cf %s

- name: /etc/sudoers.d/
  file:
    path:   /etc/sudoers.d
    state:  directory
